# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/arkady/Documents/Vivado Projects/TDCTwoStage/TDCTwoStage.srcs/sources_1/ip/FifoTDL/FifoTDL.xci
# IP: The module: 'FifoTDL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arkady/Documents/Vivado Projects/TDCTwoStage/TDCTwoStage.srcs/sources_1/ip/FifoTDL/FifoTDL.xdc
# XDC: The top module name and the constraint reference have the same name: 'FifoTDL'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/arkady/Documents/Vivado Projects/TDCTwoStage/TDCTwoStage.srcs/sources_1/ip/FifoTDL/FifoTDL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FifoTDL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/arkady/Documents/Vivado Projects/TDCTwoStage/TDCTwoStage.srcs/sources_1/ip/FifoTDL/FifoTDL.xci
# IP: The module: 'FifoTDL' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/arkady/Documents/Vivado Projects/TDCTwoStage/TDCTwoStage.srcs/sources_1/ip/FifoTDL/FifoTDL.xdc
# XDC: The top module name and the constraint reference have the same name: 'FifoTDL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /home/arkady/Documents/Vivado Projects/TDCTwoStage/TDCTwoStage.srcs/sources_1/ip/FifoTDL/FifoTDL_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'FifoTDL'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
